apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bigipreport
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bigipreport/frontend
        volumeMounts:
          - name: bigipreport-underlay
            mountPath: usr/share/nginx/html
            readOnly: true
        ports:
        - containerPort: 80
      volumes:
        - name: bigipreport-underlay
          persistentVolumeClaim:
            claimName: bigipreport-pvc
