apiVersion: v1
kind: Service
metadata:
  name: bigipreport
  namespace: "{{ .Values.namespace }}"
  labels:
    app: bigipreport
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
