apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bigipreport
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bigipreport/frontend
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
          - name: bigipreport-underlay
            mountPath: usr/share/nginx/html
            readOnly: true
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
      volumes:
        - name: bigipreport-underlay
          persistentVolumeClaim:
            claimName: bigipreport-pvc
