{{- if .Values.dataCollector.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: bigipreport-secrets
  namespace: bigipreport
data:
  {{- toYaml .Values.dataCollector.credentials | nindent 2 }}
{{- end }}